# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navi',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
