# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='\u5185\u5bb9\u9879')),
                ('remarks', models.CharField(max_length=100, verbose_name='\u5907\u6ce8')),
                ('content_status', models.CharField(max_length=10, verbose_name='\u72b6\u6001')),
                ('content_time', models.DateTimeField(auto_now_add=True, verbose_name='\u65f6\u95f4')),
            ],
        ),
    ]
